version: "2"

run:
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 8
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 50

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
