version: 2

project_name: zepctl

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/zepctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Only build darwin/arm64, not darwin/amd64
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w
      - -X github.com/getzep/zepctl/internal/cli.version={{.Version}}
      - -X github.com/getzep/zepctl/internal/cli.commit={{.Commit}}
      - -X github.com/getzep/zepctl/internal/cli.date={{.Date}}
    binary: zepctl

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Use zip for Windows (if added later)
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - docs/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

# GitHub release
release:
  github:
    owner: getzep
    name: zepctl
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew tap getzep/zepctl https://github.com/getzep/zepctl.git
    brew install zepctl
    ```

    ### Binary Download
    Download the appropriate binary for your platform from the assets below.

    **macOS users:** If you see "zepctl cannot be opened because the developer cannot be verified", run:
    ```bash
    xattr -d com.apple.quarantine /path/to/zepctl
    ```

    ### Verify Checksums
    ```bash
    sha256sum -c checksums.txt
    ```
