# This file was generated by GoReleaser. DO NOT EDIT.
cask "zepctl" do
  name "zepctl"
  desc "CLI for administering Zep projects"
  homepage "https://github.com/getzep/zepctl"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zepctl"

  on_macos do
    on_arm do
      url "https://github.com/getzep/zepctl/releases/download/v#{version}/zepctl_#{version}_darwin_arm64.tar.gz"
      sha256 "a5bd6bc9fb9a5c69d2680fa6ee6d6b83e0d93cb38332625e33d651bf289106a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/getzep/zepctl/releases/download/v#{version}/zepctl_#{version}_linux_amd64.tar.gz"
      sha256 "2284a5ad52454d191272cf20ac6a54545e322007d6a8e300a35a825b5a1592ed"
    end
    on_arm do
      url "https://github.com/getzep/zepctl/releases/download/v#{version}/zepctl_#{version}_linux_arm64.tar.gz"
      sha256 "5f0e962c3c406b8bc8fa9fe7424714b81c004b7afb9fb11eb8ecd31224ca7455"
    end
  end

  # No zap stanza required
end
